"""
Glossary Data Module
Contains all glossary terms with categories, formulas, and related terms
"""

def get_glossary():
    """Return the complete glossary"""
    return [
        {"term": "Anomaly Score", "category": "Statistics", 
         "definition": "Value 0-1 indicating deviation from normal patterns. >0.5 triggers alert.", 
         "formula": "Z-score = (x - μ)/σ; Isolation Forest scores", 
         "related": ["Z-score", "Isolation Forest"]},
        {"term": "Z-score", "category": "Statistics", 
         "definition": "Number of standard deviations from mean.", 
         "formula": "Z = (x - μ)/σ", 
         "related": ["Anomaly Score"]},
        {"term": "Isolation Forest", "category": "ML", 
         "definition": "Anomaly detection algorithm that isolates observations by randomly selecting features.", 
         "formula": "Anomaly score = 2^{-E(h(x))/c(n)}", 
         "related": ["Anomaly Score"]},
        {"term": "FP-Growth", "category": "Data Mining", 
         "definition": "Frequent Pattern Growth algorithm for mining frequent itemsets without candidate generation.", 
         "formula": "Support = count(itemset)/total transactions", 
         "related": ["Association Rules", "Support"]},
        {"term": "Support", "category": "Data Mining", 
         "definition": "Frequency of an itemset in the dataset.", 
         "formula": "Supp(X) = #transactions containing X / total transactions", 
         "related": ["FP-Growth", "Confidence"]},
        {"term": "Confidence", "category": "Data Mining", 
         "definition": "Probability of consequent given antecedent.", 
         "formula": "Conf(X→Y) = Supp(X∪Y)/Supp(X)", 
         "related": ["Support", "Lift"]},
        {"term": "Lift", "category": "Data Mining", 
         "definition": "How much more likely consequent occurs when antecedent occurs.", 
         "formula": "Lift = Confidence / Supp(Y)", 
         "related": ["Confidence"]},
        {"term": "LDA", "category": "NLP", 
         "definition": "Latent Dirichlet Allocation - generative model for topic discovery.", 
         "formula": "p(word|doc) = Σ_k p(word|topic_k) · p(topic_k|doc)", 
         "related": ["Topic Modeling", "Coherence Score"]},
        {"term": "TF-IDF", "category": "NLP", 
         "definition": "Term Frequency-Inverse Document Frequency for word importance.", 
         "formula": "TF-IDF = tf * log(N/df)", 
         "related": ["Vectorization"]},
        {"term": "VADER", "category": "NLP", 
         "definition": "Valence Aware Dictionary and sEntiment Reasoner - rule-based sentiment for social media.", 
         "formula": "compound = normalize(Σ valence scores + rules)", 
         "related": ["Sentiment Analysis"]},
        {"term": "ROC Curve", "category": "ML", 
         "definition": "True Positive Rate vs False Positive Rate at thresholds.", 
         "formula": "TPR = TP/(TP+FN), FPR = FP/(FP+TN)", 
         "related": ["AUC", "Confusion Matrix"]},
        {"term": "AUC", "category": "ML", 
         "definition": "Area Under the ROC Curve - measure of classifier performance.", 
         "formula": "∫_0^1 TPR(FPR) dFPR", 
         "related": ["ROC Curve"]},
        {"term": "Confusion Matrix", "category": "ML", 
         "definition": "Table of TP, FP, TN, FN.", 
         "formula": "[[TN, FP], [FN, TP]]", 
         "related": ["Accuracy", "Precision", "Recall"]},
        {"term": "SVM", "category": "ML", 
         "definition": "Support Vector Machine - finds optimal hyperplane for classification.", 
         "formula": "min ||w||^2 s.t. y_i(w·x_i+b) ≥ 1", 
         "related": ["Kernel Trick"]},
        {"term": "Random Forest", "category": "ML", 
         "definition": "Ensemble of decision trees with bagging.", 
         "formula": "Majority vote of T trees", 
         "related": ["Decision Tree"]},
        {"term": "Naive Bayes", "category": "ML", 
         "definition": "Probabilistic classifier assuming feature independence.", 
         "formula": "P(C|X) ∝ P(C)∏P(x_i|C)", 
         "related": ["Bayes Theorem"]},
        {"term": "VIX", "category": "Finance", 
         "definition": "CBOE Volatility Index - market's expectation of 30-day volatility.", 
         "formula": "Derived from S&P 500 option prices", 
         "related": ["Volatility"]},
        {"term": "Silhouette Score", "category": "ML", 
         "definition": "Clustering quality metric ranging from -1 (poor) to 1 (excellent).", 
         "formula": "s = (b-a)/max(a,b)", 
         "related": ["Clustering"]},
        {"term": "K-Means", "category": "ML", 
         "definition": "Clustering algorithm partitioning data into K clusters.", 
         "formula": "min ∑∑||x - μ_k||^2", 
         "related": ["Silhouette Score"]},
        {"term": "Word Cloud", "category": "Visualization", 
         "definition": "Visual representation of word frequency where size indicates importance.", 
         "formula": "Font size ∝ frequency", 
         "related": ["TF-IDF"]},
        {"term": "F1 Score", "category": "ML", 
         "definition": "Harmonic mean of precision and recall.", 
         "formula": "F1 = 2 * (precision * recall) / (precision + recall)", 
         "related": ["Precision", "Recall"]}
    ]